Repository ASFHyP3/hyp3-sdk, pull requests merged in 2020-10, with the labels that each got.

#13 RELEASE: allow sdk to search by name
  CHANGELOG.md
  README.md
  hyp3_sdk/hyp3.py
Labels: minor

#16 Update README for docs website
  README.md
Labels: documentation

#17 RELEASE: just ship the documentation changes
  README.md
Labels: patch

#19 RELEASE: v0.2.1 -- try again
  .github/workflows/changelog.yml
  CHANGELOG.md
Labels: patch

#22 Update docs for feedback on release
  CHANGELOG.md
  README.md
  docs/README.md
  docs/index.md
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  mkdocs.yml
Labels: bumpless

#21 Release documentation update
  CHANGELOG.md
  README.md
  conda-env.yml
  docs/README.md
  docs/index.md
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  mkdocs.yml
Labels: patch
