Repository ASFHyP3/hyp3-sdk, pull requests merged in 2020-11, with the labels that each got.

#23 Trigger SDK version bumb in HyP3 Docs
  .github/workflows/release.yml
Labels: CI/CD, bumpless

#24 SDK API refactor
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  conda-env.yml
  hyp3_sdk/__init__.py
  hyp3_sdk/config.py
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  setup.py
  tests/conftest.py
  tests/test_hyp3.py
  tests/test_job.py
  tests/test_jobs.py
  tests/test_util.py
Labels: minor

#25 RELEASE: 0.3.0
  .github/workflows/release.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  conda-env.yml
  hyp3_sdk/__init__.py
  hyp3_sdk/config.py
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  setup.py
  tests/conftest.py
  tests/test_hyp3.py
  tests/test_job.py
  tests/test_jobs.py
  tests/test_util.py
Labels: minor

#29 RELEASE: 0.3.0 attempt 2
  .github/workflows/release.yml
Labels: minor

#35 Don't need refs/heads for branch spec in workflow dispatch
  .github/workflows/release.yml
Labels: bumpless

#38 Correctly specify minimum python version
  .github/workflows/static-analysis.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  conda-env.yml
  hyp3_sdk/__init__.py
  setup.py
Labels: bug

#39 RELEASE 0.3.1
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  conda-env.yml
  docs/index.md
  hyp3_sdk/__init__.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  setup.py
  tests/test_jobs.py
  tests/test_util.py
Labels: patch

#40 Add conda to install docs and some README badges
  README.md
  docs/index.md
Labels: bumpless

#44 fix typo in index.md example
  docs/index.md
Labels: bumpless

#45 RELEASE: 0.3.2
  CHANGELOG.md
  README.md
  conda-env.yml
  docs/index.md
  hyp3_sdk/jobs.py
  tests/test_jobs.py
Labels: patch

#46 A couple of tweaks
  README.md
  docs/index.md
  hyp3_sdk/jobs.py
Labels: bumpless
