Repository ASFHyP3/hyp3-sdk, pull requests merged in 2021-02, with the labels that each got.

#65 Release basic ASF Search module
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  conda-env.yml
  docs/README.md
  docs/index.md
  hyp3_sdk/asf_search.py
  hyp3_sdk/jobs.py
  mkdocs.yml
  tests/test_asf_search.py
Labels: minor

#66 Baseline typo
  hyp3_sdk/asf_search.py
  tests/test_asf_search.py
Labels: bumpless

#70 All preparation and submission of multiple jobs
  CHANGELOG.md
  conda-env.yml
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  tests/test_hyp3.py
Labels: enhancement

#71 Iterable batch
  CHANGELOG.md
  hyp3_sdk/jobs.py
  tests/test_jobs.py
Labels: enhancement

#75 descriptive submission errors
  hyp3_sdk/hyp3.py
Labels: bumpless

#74 Release v0.5.0
  CHANGELOG.md
  conda-env.yml
  hyp3_sdk/asf_search.py
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  setup.py
  tests/test_asf_search.py
  tests/test_hyp3.py
  tests/test_jobs.py
Labels: minor

#76 fix indentation typo in setup.py
  setup.py
Labels: bumpless

#77 Remove unnecessary package
  conda-env.yml
Labels: bumpless
