Repository ASFHyP3/hyp3-sdk, pull requests merged in 2021-03, with the labels that each got.

#83 Fix whitespace
  hyp3_sdk/hyp3.py
Labels: bumpless

#82 Binder
  .github/workflows/test-and-build.yml
  docs/sdk_example.ipynb
  environment.yml
Labels: bumpless, documentation

#86 Faster, cleaner github actions
  .github/workflows/distribute.yml
  .github/workflows/release.yml
  .github/workflows/test-and-tag.yml
  environment.yml
Labels: CI/CD, bumpless

#93 Update examples notebook for submit/prepare keyword arguments
  docs/sdk_example.ipynb
Labels: bumpless, documentation

#95 make helper raise for status functions private
  hyp3_sdk/asf_search.py
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  tests/test_exceptions.py
Labels: bumpless

#94 Release password/username prompt, error messaging, asf_search improvements, fixed auth error
  .github/workflows/distribute.yml
  .github/workflows/release.yml
  .github/workflows/test-and-tag.yml
  .trufflehog.txt
  CHANGELOG.md
  docs/sdk_example.ipynb
  environment.yml
  hyp3_sdk/asf_search.py
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
  setup.py
  tests/test_asf_search.py
  tests/test_exceptions.py
  tests/test_hyp3.py
Labels: minor

#96 fix distribute workflow
  .github/workflows/distribute.yml
Labels: CI/CD, bug, bumpless

#99 Fix example notebook title
  docs/sdk_example.ipynb
Labels: bumpless

#101 change docs repo
  .github/workflows/release.yml
Labels: CI/CD, bumpless

#104 RELEASE: 1.0.0
  .github/workflows/distribute.yml
  .github/workflows/release.yml
  CHANGELOG.md
  docs/sdk_example.ipynb
  hyp3_sdk/exceptions.py
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  tests/test_exceptions.py
  tests/test_hyp3.py
  tests/test_jobs.py
Labels: major

#106 fix bug in distribute workflow
  .github/workflows/distribute.yml
Labels: bumpless

#110 pin setup-miniconda to 2.0.1
  .github/workflows/distribute.yml
  .github/workflows/test-and-tag.yml
Labels: bumpless
