Repository ASFHyP3/hyp3-sdk, pull requests merged in 2021-06, with the labels that each got.

#125 Handle missing ipywidgets when using a tqdm progress bar
  CHANGELOG.md
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
  hyp3_sdk/util.py
Labels: bug

#129 Tests for find_jobs() w/ and w/o timezone
  tests/test_hyp3.py
Labels: bumpless

#126 Notify downstream of new version
  .github/queries/associated-pr.query.yml
  .github/workflows/notify-downstream.yml
  .github/workflows/release.yml
Labels: CI/CD, bumpless
