Repository ASFHyP3/hyp3-sdk, pull requests merged in 2023-01, with the labels that each got.

#181 Remove duplicated period in download warning
  hyp3_sdk/jobs.py
Labels: bumpless

#182 Release v1.7.3
  CHANGELOG.md
  hyp3_sdk/hyp3.py
  hyp3_sdk/jobs.py
Labels: patch

#185 fix tag in reusable workflow
  .github/workflows/static-analysis.yml
Labels: CI/CD, bumpless

#186 Release v1.7.4
  .github/workflows/distribute.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test-and-tag.yml
  CHANGELOG.md
  MANIFEST.in
  environment.yml
  hyp3_sdk/__init__.py
  postBuild
  pyproject.toml
  setup.py
  src/hyp3_sdk/__init__.py
  src/hyp3_sdk/config.py
  src/hyp3_sdk/exceptions.py
  src/hyp3_sdk/hyp3.py
  src/hyp3_sdk/jobs.py
  src/hyp3_sdk/util.py
Labels: patch

#187 fix path to README
  pyproject.toml
Labels: bug, bumpless

#190 Update CI/CD workflow to v0.7.0
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test-and-tag.yml
  .github/workflows/test.yml
Labels: CI/CD, bumpless
