Repository ASFHyP3/hyp3-sdk, pull requests merged in 2024-02, with the labels that each got.

#260 Release v6.0.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  CHANGELOG.md
  src/hyp3_sdk/hyp3.py
  src/hyp3_sdk/jobs.py
  tests/conftest.py
  tests/test_hyp3.py
  tests/test_jobs.py
Labels: major

#264 Release v6.1.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  .trufflehog.txt
  CHANGELOG.md
  src/hyp3_sdk/hyp3.py
  src/hyp3_sdk/jobs.py
  tests/test_hyp3.py
  tests/test_jobs.py
Labels: minor

#265 Drop verify step for PyPI distribution
  .github/workflows/distribute.yml
Labels: CI/CD, bumpless
