Repository ASFHyP3/hyp3-sdk, pull requests merged in 2024-05, with the labels that each got.

#273 Update dependabot.yml to weekly
  .github/dependabot.yml
Labels: bumpless

#275 Check user is whitelisted after authentication
  CHANGELOG.md
  src/hyp3_sdk/hyp3.py
  tests/conftest.py
  tests/test_hyp3.py
Labels: patch

#277 remove extra space
  src/hyp3_sdk/hyp3.py
Labels: bumpless

#276 Release v6.2.0
  .github/dependabot.yml
  .github/workflows/distribute.yml
  CHANGELOG.md
  src/hyp3_sdk/hyp3.py
  src/hyp3_sdk/jobs.py
  tests/conftest.py
  tests/test_hyp3.py
  tests/test_jobs.py
Labels: minor
