Repository ASFHyP3/hyp3-sdk, pull requests merged in 2025-06, with the labels that each got.

#357 Release v7.6.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  requirements-static.txt
  src/hyp3_sdk/hyp3.py
  tests/test_hyp3.py
Labels: minor

#359 Notebook updates
  docs/hyp3_authentication.ipynb
  docs/hyp3_job_name_change.ipynb
Labels: bumpless

#362 Release v7.7.1
  CHANGELOG.md
  docs/hyp3_authentication.ipynb
  docs/hyp3_job_name_change.ipynb
  docs/sdk_example.ipynb
  docs/search_other_user_jobs.ipynb
Labels: patch

#365 dependabot groups
  .github/dependabot.yml
Labels: bumpless
